[package]
name = "food_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="3.2.22", features=["derive"]}
recipe-scraper = {path= "../recipe-scraper"}
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
ingredient= {path = "../ingredient-parser"}