ignore:
  - "bin/"
  - "food-app/"
  - "food-cli/"
  - "food_cli/"
  - "food_ui/"
  - "food_web/"
  - "ingredient-wasm/"
  - "ingredient-parser/benches/"
  - "ingredient-parser/tests/"
  - "recipe-scraper/tests/"
  - "recipe_scraper_fetcher/tests/"
