// Single source for curated models, legacy IDs, routing metadata and USD rates.
// Cache rates preserve existing estimates; see ../MODELS.md before repricing.
pub const DEFAULT_MODEL: &str = "gemini-2.5-flash";
static ENTRIES: &[Entry] = &[
    Entry {
        model: Model {
            id: "@cf/zai-org/glm-4.7-flash",
            label: "GLM 4.7 Flash",
            provider: "workers-ai",
            enabled: true,
            status: "Experimental; 4/5 sample groups failed validation or timed out",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/models/glm-4.7-flash/",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.06,
            output: 0.4,
            cache_read: 0.006,
            cache_write: 0.075,
        }),
    },
    Entry {
        model: Model {
            id: "@cf/zai-org/glm-5.3-flash",
            label: "GLM 5.3 Flash",
            provider: "workers-ai",
            enabled: true,
            status: "Cross-book: Charred, Nopalito and Sunday Suppers source checks pass after recovery; Thai/Tacos still under review",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/models/glm-5.3-flash/",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.15,
            output: 0.5,
            cache_read: 0.03,
            cache_write: 0.1875,
        }),
    },
    Entry {
        model: Model {
            id: "@cf/zai-org/glm-5.3",
            label: "GLM 5.3",
            provider: "workers-ai",
            enabled: true,
            status: "Sample verified: 13/13 recipes",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/models/glm-5.3/",
        },
        listed: true,
        rates: Some(Rates {
            input: 1.4,
            output: 4.4,
            cache_read: 0.26,
            cache_write: 1.75,
        }),
    },
    Entry {
        model: Model {
            id: "@cf/deepseek-ai/deepseek-v4-flash-0731",
            label: "DeepSeek V4 Flash",
            provider: "workers-ai",
            enabled: true,
            status: "Dessert Person sample: 13/13 in two runs; difficult Nopalito chunk timed out",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/models/deepseek-v4-flash-0731/",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.44,
            output: 1.32,
            cache_read: 0.014,
            cache_write: 0.55,
        }),
    },
    Entry {
        model: Model {
            id: "@cf/google/gemma-4-26b-a4b-it",
            label: "Gemma 4 26B A4B",
            provider: "workers-ai",
            enabled: true,
            status: "Experimental; initial 13/13 sample pass, repeat lost a chunk",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/models/gemma-4-26b-a4b-it/",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.1,
            output: 0.3,
            cache_read: 0.010000000000000002,
            cache_write: 0.125,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-2.5-flash",
            label: "Gemini 2.5 Flash",
            provider: "google-ai-studio",
            enabled: true,
            status: "Existing baseline",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.3,
            output: 2.5,
            cache_read: 0.03,
            cache_write: 0.375,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-2.5-flash-lite",
            label: "Gemini 2.5 Flash-Lite",
            provider: "google-ai-studio",
            enabled: true,
            status: "Compatible; not benchmarked",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.1,
            output: 0.4,
            cache_read: 0.010000000000000002,
            cache_write: 0.125,
        }),
    },
    Entry {
        model: Model {
            id: "claude-haiku-4-5",
            label: "Claude Haiku 4.5",
            provider: "anthropic",
            enabled: true,
            status: "Experimental; source validation failures in evaluation",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: true,
        rates: Some(Rates {
            input: 1.0,
            output: 5.0,
            cache_read: 0.1,
            cache_write: 1.25,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-3.5-flash-lite",
            label: "Gemini 3.5 Flash-Lite",
            provider: "google-ai-studio",
            enabled: true,
            status: "Experimental; evaluated 2026-09-09",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.3,
            output: 2.5,
            cache_read: 0.03,
            cache_write: 0.375,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-3.7-flash",
            label: "Gemini 3.7 Flash",
            provider: "google-ai-studio",
            enabled: true,
            status: "Experimental; evaluated 2026-09-09",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.75,
            output: 3.75,
            cache_read: 0.07500000000000001,
            cache_write: 0.9375,
        }),
    },
    Entry {
        model: Model {
            id: "claude-sonnet-5",
            label: "Claude Sonnet 5",
            provider: "anthropic",
            enabled: true,
            status: "Experimental; evaluated 2026-09-09",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: true,
        rates: Some(Rates {
            input: 2.0,
            output: 10.0,
            cache_read: 0.2,
            cache_write: 2.5,
        }),
    },
    Entry {
        model: Model {
            id: "gpt-5.6-luna",
            label: "GPT-5.6 Luna",
            provider: "openai",
            enabled: true,
            status: "Experimental; Responses verified 2026-09-09",
            transport: "responses",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.2,
            output: 1.2,
            cache_read: 0.020000000000000004,
            cache_write: 0.25,
        }),
    },
    Entry {
        model: Model {
            id: "@cf/moonshotai/kimi-k2.6",
            label: "Kimi K2.6",
            provider: "workers-ai",
            enabled: false,
            status: "Experimental; Gateway authenticated, recipe requests timed out",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/platform/pricing/",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.95,
            output: 4.0,
            cache_read: 0.16,
            cache_write: 1.1875,
        }),
    },
    Entry {
        model: Model {
            id: "@cf/moonshotai/kimi-k2.7-code",
            label: "Kimi K2.7 Code",
            provider: "workers-ai",
            enabled: true,
            status: "Cross-book: Charred and Sunday Suppers source checks pass after recovery; provider and schema failures remain",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.cloudflare.com/workers-ai/platform/pricing/",
        },
        listed: true,
        rates: Some(Rates {
            input: 0.95,
            output: 4.0,
            cache_read: 0.19,
            cache_write: 1.1875,
        }),
    },
    Entry {
        model: Model {
            id: "claude-haiku-4-5-20251001",
            label: "claude-haiku-4-5-20251001",
            provider: "anthropic",
            enabled: false,
            status: "Legacy compatibility",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 1.0,
            output: 5.0,
            cache_read: 0.1,
            cache_write: 1.25,
        }),
    },
    Entry {
        model: Model {
            id: "claude-sonnet-4-5",
            label: "claude-sonnet-4-5",
            provider: "anthropic",
            enabled: false,
            status: "Legacy compatibility",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 3.0,
            output: 15.0,
            cache_read: 0.30000000000000004,
            cache_write: 3.75,
        }),
    },
    Entry {
        model: Model {
            id: "claude-sonnet-4-6",
            label: "claude-sonnet-4-6",
            provider: "anthropic",
            enabled: false,
            status: "Legacy compatibility",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 3.0,
            output: 15.0,
            cache_read: 0.30000000000000004,
            cache_write: 3.75,
        }),
    },
    Entry {
        model: Model {
            id: "claude-opus-4-5",
            label: "claude-opus-4-5",
            provider: "anthropic",
            enabled: false,
            status: "Legacy compatibility",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        }),
    },
    Entry {
        model: Model {
            id: "claude-opus-4-5-20251101",
            label: "claude-opus-4-5-20251101",
            provider: "anthropic",
            enabled: false,
            status: "Legacy compatibility",
            transport: "messages",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-2.0-flash",
            label: "gemini-2.0-flash",
            provider: "google-ai-studio",
            enabled: false,
            status: "Legacy compatibility",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 0.1,
            output: 0.4,
            cache_read: 0.010000000000000002,
            cache_write: 0.125,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-2.0-flash-lite",
            label: "gemini-2.0-flash-lite",
            provider: "google-ai-studio",
            enabled: false,
            status: "Legacy compatibility",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 0.075,
            output: 0.3,
            cache_read: 0.0075,
            cache_write: 0.09375,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-2.5-flash-002",
            label: "gemini-2.5-flash-002",
            provider: "google-ai-studio",
            enabled: false,
            status: "Legacy compatibility",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 0.3,
            output: 2.5,
            cache_read: 0.03,
            cache_write: 0.375,
        }),
    },
    Entry {
        model: Model {
            id: "gemini-2.5-flash-lite-preview",
            label: "gemini-2.5-flash-lite-preview",
            provider: "google-ai-studio",
            enabled: false,
            status: "Legacy compatibility",
            transport: "gateway-unified-chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://ai.google.dev/gemini-api/docs/pricing",
        },
        listed: false,
        rates: Some(Rates {
            input: 0.1,
            output: 0.4,
            cache_read: 0.010000000000000002,
            cache_write: 0.125,
        }),
    },
    Entry {
        model: Model {
            id: "gpt-4o-mini",
            label: "gpt-4o-mini",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
    Entry {
        model: Model {
            id: "gpt-4o",
            label: "gpt-4o",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
    Entry {
        model: Model {
            id: "gpt-4.1-mini",
            label: "gpt-4.1-mini",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
    Entry {
        model: Model {
            id: "o3-mini",
            label: "o3-mini",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
    Entry {
        model: Model {
            id: "o1",
            label: "o1",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
    Entry {
        model: Model {
            id: "o3",
            label: "o3",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
    Entry {
        model: Model {
            id: "o4-mini",
            label: "o4-mini",
            provider: "openai",
            enabled: false,
            status: "Legacy compatibility",
            transport: "chat-completions",
            max_output_tokens: 16000,
            pricing_checked: "2026-09-09",
            pricing_source: "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        },
        listed: false,
        rates: None,
    },
];
