on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: jetli/wasm-pack-action@v0.4.0
      # - run: wasm-pack build ingredient-wasm
      # - run: mkdir -p demo-site/src/wasm && cp -r ingredient-wasm/pkg demo-site/src/wasm
      #   working-directory: demo-site
      # - run: yarn && yarn build
      #   working-directory: demo-site
      - name: Build site
        run: make build-demo-site
      - name: Publish
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 9f10f078d35d86c78dedece2300a6b88
          projectName: ingredient
          directory: demo-site/dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
